[build-system]
build-backend = "cmeel"
requires = [
  "cmeel[build]",
  "jrl-cmakemodules[build]"
]

[project]
description = "Plotting tools for HPP"
license = "BSD-2-Clause"
name = "hpp-plot"
requires-python = ">= 3.10"
version = "9.0.0"

[project.urls]
homepage = "https://github.com/cmake-wheel/hpp-plot"
repository = "https://github.com/cmake-wheel/hpp-plot.git"
upstream = "https://github.com/humanoid-path-planner/hpp-plot"

[tool.ruff]
extend-exclude = ["cmake"]

[tool.ruff.lint]
extend-select = ["I", "NPY", "RUF", "UP", "W"]

[tool.tomlsort]
all = true
